export const DISPLAY_ALERT = "SHOW_ALERT";
export const CLEAR_ALERT = "CLEAR_ALERT";

// export const REGISTER_USER_BEGIN = "REGISTER_USER_BEGIN";
// export const REGISTER_USER_SUCCESS = "REGISTER_USER_SUCCESS";
// export const REGISTER_USER_ERROR = "REGISTER_USER_ERROR";
// export const LOGIN_USER_BEGIN = "LOGIN_USER_BEGIN";
// export const LOGIN_USER_SUCCESS = "LOGIN_USER_SUCCESS";
// export const LOGIN_USER_ERROR = "LOGIN_USER_ERROR";

export const SETUP_USER_BEGIN = "SETUP_USER_BEGIN";
export const SETUP_USER_SUCCESS = "SETUP_USER_SUCCESS";
export const SETUP_USER_ERROR = "SETUP_USER_ERROR";

export const TOGGLE_SIDEBAR = "TOGGLE_SIDEBAR";
export const LOGOUT_USER = "LOGOUT_USER";

export const UPDATE_USER_BEGIN = "UPDATE_USER_BEGIN";
export const UPDATE_USER_SUCCESS = "UPDATE_USER_SUCCESS";
export const UPDATE_USER_ERROR = "UPDATE_USER_ERROR";

export const HANDLE_CHANGE = "HANDLE_CHANGE";

export const CLEAR_VALUES = "CLEAR_VALUES";

export const CREATE_JOB_BEGIN = "CREATE_JOB_BEGIN";
export const CREATE_JOB_SUCCESS = "CREATE_JOB_SUCCESS";
export const CREATE_JOB_ERROR = "CREATE_JOB_ERROR";

export const GET_JOBS_BEGIN = "GET_JOBS_BEGIN";
export const GET_JOBS_SUCCESS = "GET_JOBS_SUCCESS";

export const SET_EDIT_JOB = "SET_EDIT_JOB";

export const DELETE_JOB_BEGIN = "DELETE_JOB_BEGIN";

export const EDIT_JOB_BEGIN = "EDIT_JOB_BEGIN";
export const EDIT_JOB_SUCCESS = "EDIT_JOB_SUCCESS";
export const EDIT_JOB_ERROR = "EDIT_JOB_ERROR";

export const SHOW_STATS_BEGIN = "SHOW_STATS_BEGIN";
export const SHOW_STATS_SUCCESS = "SHOW_STATS_SUCCESS";

export const CLEAR_FILTERS = "CLEAR_FILTERS";

export const CHANGE_PAGE = "CHANGE_PAGE";

export const CREATE_TODO_BEGIN = "CREATE_TODO_BEGIN";
export const CREATE_TODO_SUCCESS = "CREATE_TODO_SUCCESS";
export const CREATE_TODO_ERROR = "CREATE_TODO_ERROR";

export const GET_TODO_BEGIN = "GET_TODO_BEGIN";
export const GET_TODO_SUCCESS = "GET_TODO_SUCCESS";
export const CLEAR_TODO_VALUES = "CLEAR_TODO_VALUES";

export const SET_EDIT_TODO = "SET_EDIT_TODO";
export const EDIT_TODO_BEGIN = "EDIT_TODO_BEGIN";
export const EDIT_TODO_SUCCESS = "EDIT_TODO_SUCCESS";
export const EDIT_TODO_ERROR = "EDIT_TODO_ERROR";

export const DELETE_TODO_BEGIN = "DELETE_TODO_BEGIN";

export const CREATE_LOG_BEGIN = "CREATE_LOG_BEGIN";
export const CREATE_LOG_SUCCESS = "CREATE_LOG_SUCCESS";
export const CREATE_LOG_ERROR = "CREATE_LOG_ERROR";

export const GET_LOGS_BEGIN = "GET_LOGS_BEGIN";
export const GET_LOGS_SUCCESS = "GET_LOGS_SUCCESS";

export const SET_EDIT_LOG = "SET_EDIT_LOG";

export const DELETE_LOG_BEGIN = "DELETE_LOG_BEGIN";
export const CLEAR_LOG_VALUES = "CLEAR_LOG_VALUES";
export const EDIT_LOG_BEGIN = "EDIT_LOG_BEGIN";
export const EDIT_LOG_SUCCESS = "EDIT_LOG_SUCCESS";
export const EDIT_LOG_ERROR = "EDIT_LOG_ERROR";

export const RESET_TIMERS = "RESET_TIMERS";
export const START_TIMER = "START_TIMER";
export const TOGGLE_TIMER_LABEL = "TOGGLE_TIMER_LABEL";
export const TOGGLE_ISBUSY_INDICATOR = "TOGGLE_ISBUSY_INDICATOR";
export const INCREASE_BREAK_VALUE = "INCREASE_BREAK_VALUE";
export const DECREASE_BREAK_VALUE = "DECREASE_BREAK_VALUE";
export const INCREASE_SESSION_VALUE = "INCREASE_SESSION_VALUE";
export const DECREASE_SESSION_VALUE = "DECREASE_SESSION_VALUE";

export const CREATE_BOOKMARK_BEGIN = "CREATE_BOOKMARK_BEGIN";
export const CREATE_BOOKMARK_SUCCESS = "CREATE_BOOKMARK_SUCCESS";
export const CREATE_BOOKMARK_ERROR = "CREATE_BOOKMARK_ERROR";

export const GET_BOOKMARK_BEGIN = "GET_BOOKMARK_BEGIN";
export const GET_BOOKMARK_SUCCESS = "GET_BOOKMARK_SUCCESS";

export const SET_EDIT_BOOKMARK = "SET_EDIT_BOOKMARK";

export const DELETE_BOOKMARK_BEGIN = "DELETE_BOOKMARK_BEGIN";
export const CLEAR_BOOKMARK_VALUES = "CLEAR_BOOKMARK_VALUES";
export const EDIT_BOOKMARK_BEGIN = "EDIT_BOOKMARK_BEGIN";
export const EDIT_BOOKMARK_SUCCESS = "EDIT_BOOKMARK_SUCCESS";
export const EDIT_BOOKMARK_ERROR = "EDIT_BOOKMARK_ERROR";
